baseURL = "https://timblog.z19.web.core.windows.net/"
languageCode = "en-us"
title = "iconic sections"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "localhost"

[params]
	subtitle = "discord and hyperbole"
	# "a ray of hyperbole"
	# "discord and hyperbole"
	# "obtuse discourse"
	# "a point of discourse"
	# "a slice of hyperbole"
	# "parabolic"
	# "circular reseasoning"
	# "elliptical"
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["post","page"]
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/tsadams1973"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/tsadams1973"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
