baseURL = "https://timblog.z19.web.core.windows.net/"
disablePathToLower = true
languageCode = "en-us"
title = "iconic sections"
theme = "docter"

[params]
  # the name of your project and a link back to the home page
  home = "iconic sections"
  logourl = "images/Covatrix_Icon 2.png"
  logoalt = "covatrix"

  author = "@tsadams1973"
  author_url= "https://twitter.com/tsadams1973"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["post"]

